### ISSUE TITLE
 Import sample data(include images) into database

### ISSUE THREAD

**Issue by ttaliacc** [BU-Spark/se-Symbiota-portal#11]
Need some dummy data to test the image function. Have reached out to the client, but the given instructions didn't work. 

### Waiting on issues
- #10 

###Resource may help: 
- https://www.gbif.org/occurrence/gallery?taxon_key=3985570 (GBIF aggregator)
- https://drive.google.com/file/d/17mPEgmhIQt1R49RSLnVkMbO5x-UPwMEi/view?usp=share_link (instruction given by the client)

**Comment by ttaliacc** [comment]
I think you made some progress on this issue? @Tian-Tan

**Comment by Tian-Tan** [comment]
Yes, sample data for the omoccurrences table and the images table are imported from the HUH TEST data, albeit using many manual mappings in the process. The sample data should be enough for testing purposes now.
