### ISSUE TITLE
Clarification required on database batch tables

### ISSUE THREAD

**Issue by Tian-Tan** [BU-Spark/se-Symbiota-portal#19]
![Batch tables](https://github.com/BU-Spark/se-Symbiota-portal/assets/101669234/3a7390e5-da69-4368-9258-ee86d334d894)
The new tables created by the team of Summer 2022 (structure shown above) are structured for handling two different types of batches (transcription batch and image batch). We have no idea how these batches are distinct from each other. This requires clarification from the clients.

For testing purposes, the two types of batches will be treated as the same, and a restructured table shall be designed to unify them.

**Comment by Tian-Tan** [comment]
![Batch overhaul](https://github.com/BU-Spark/se-Symbiota-portal/assets/101669234/fa308205-3805-4c04-87ae-7223a05ba485)
The ER diagram above showcases the new simplified batch tables.

Some clarifications are required:
1. Are there supposed to be different types of batches (transcription batch and image batch), or is there only a single general batch?
2. Are there any other uses for the batch other than the data entry process? If so, should the batch contain other metadata?

**Comment by ttaliacc** [comment]
Solved in the client meeting. Look at the meeting notes.

**Comment by ttaliacc** [comment]
Based on what the client said, we should consider barcode when we are designing the table.

We will do the research first #37 and see what we can do with this issue,
