### ISSUE TITLE
Questions regarding the whole workflow

### ISSUE THREAD

**Issue by ttaliacc** [BU-Spark/se-Symbiota-portal#23]
## (a) The work flow of the image part:

Talia's guess:
1. Upload the image through the old entry form (currently, that's the only place where we can upload images)
2. Get the corresponding image(s) from the db by occId
3. Display the image(s) in the quick entry form 
4. Based on the image, the quick entry form is generated (which comes first? the image or the quick entry form?)

## (b) Initialization workflow
How is the entire data entry process initialized? Is it something like
a. Create a new collection
b. Upload images (are they uploaded one-by-one or in bulk?)
c. Begin data entry process

## (c) Batch workflow
1. How is an image assigned to a batch?
2. How are the batches created initially?

**Comment by Tian-Tan** [comment]
The initialization step is for an admin user to upload a directory of images through FTP (bulk import). Symbiota has functions to ingest the image, team needs to enhance the ingestion to also create the transcription batch at the same time.

**Comment by ttaliacc** [comment]
So doesn't it mean that we shouldn't use the image upload page in the old entry form to upload images? But that page does connected to the image table we are currently using, and the logic conflict still exits. @Tian-Tan

**Comment by ttaliacc** [comment]
Everything is clear now, and we are making progress
