### ISSUE TITLE
What is the relationship between the image and quick entry form?

### ISSUE THREAD

**Issue by ttaliacc** [BU-Spark/se-Symbiota-portal#24]
### Questions:
1. How does the dependency work? Does the existence of a quick entry form depend on the existence of an image, or vice versa, or there is no dependency at all?
2. What is the relationship between them: one to one, one to many, or many to many? (In the old entry form, where we can upload images, we can have multiple images for each entry form, and we are able to switch between images)

**Comment by Tian-Tan** [comment]
1. How does the dependency work? Does the existence of a quick entry form depend on the existence of an image, or vice versa, or there is no dependency at all?
- The image is more important
2. What is the relationship between them: one to one, one to many, or many to many? (In the old entry form, where we can upload images, we can have multiple images for each entry form, and we are able to switch between images)
- In rare cases there can be more than one occurrence for one image, which makes it a many to many relationship. However, generally it is the case that one image only has one occurrence, and one occurrence may have more than one image

**Comment by ttaliacc** [comment]
Related issues:
- #23

**Comment by ttaliacc** [comment]
Close this issue because it's redundant
