### ISSUE TITLE
Questions about the dropdown lists

### ISSUE THREAD

**Issue by ttaliacc** [BU-Spark/se-Symbiota-portal#26]
1. Are the existing dropdown functions sufficient?
2. What is the source of the data that populates the dropdown lists? Are they from records previously entered into the database  or are they imported from a third party database?
3. Should the user be constrained to only choose from among the options provided in the dropdowns or are they supposed to be able to enter a new value too?

**Comment by ttaliacc** [comment]
Can you add your related questions? @Tian-Tan Feel free to edit the existing ones.

**Comment by Tian-Tan** [comment]
1. Are the existing dropdown functions sufficient?
- Symbiota supposedly already has their own dropdown functions, so its better to leverage them.
2. What is the source of the data that populates the dropdown lists? Are they from records previously entered into the database or are they imported from a third party database?
- The dropdowns are NOT populated through tables, but through scanning existing values
3. Should the user be constrained to only choose from among the options provided in the dropdowns or are they supposed to be able to enter a new value too?
- They should not be able to enter new values.

**Comment by ttaliacc** [comment]
Related Issues:
- #34

**Comment by ttaliacc** [comment]
#34 is in progress

**Comment by ttaliacc** [comment]
Close because of redundancy
