### ISSUE TITLE
Reduce lag for dropdown lists

### ISSUE THREAD

**Issue by Tian-Tan** [BU-Spark/se-Symbiota-portal#33]
When fully implemented, the dropdown list will be very long and will cause a lot of lag and delay. A possible solution is to let the dropdown list pop up only after a certain number of letters (3 or 4) are entered.

**Comment by ttaliacc** [comment]
### Wait for
- #34

**Comment by ttaliacc** [comment]
We will delay this issue util we figure out the ingestion function

**Comment by ttaliacc** [comment]
We use views to retrieve distinct values, so the dropdown search is very fast
