### ISSUE TITLE
Create multiple transcriptions from one image

### ISSUE THREAD

**Issue by Tian-Tan** [BU-Spark/se-Symbiota-portal#35]
It is possible for an image to have more than one barcode, and upon detecting that, the system should automatically create multiple transcriptions for each of the barcodes. The batch tables might need to be altered to accommodate this, but it is possible to just create multiple image entries with different ordinal numbers.

**Comment by ttaliacc** [comment]
I think we should split this issue in to a frontend one and a db one. @Tian-Tan

**Comment by ttaliacc** [comment]
This issue is redundant with the issue talks about the relationship between images and occurrences.
