### ISSUE TITLE
Image nav bar

### ISSUE THREAD

**Issue by Tian-Tan** [BU-Spark/se-Symbiota-portal#36]
For occurrences with more than one images, there should be a nav bar where user can navigate through the images attached to this occurrence. We simply need to filter the image table to find out the related images

**Comment by ttaliacc** [comment]
We need the image bar when an occurrence has multiple images

**Comment by ttaliacc** [comment]
The existing image window has "image nav bar". But it's not very complete? 

<img width="799" alt="Screenshot 2023-11-30 at 11 33 51" src="https://github.com/BU-Spark/se-Symbiota-portal/assets/103902059/ba4809d3-971a-4828-adbe-a0910a8e8526">

<img width="572" alt="Screenshot 2023-11-30 at 11 33 43" src="https://github.com/BU-Spark/se-Symbiota-portal/assets/103902059/3991ffbc-fa95-4013-9f01-ef3a1d49d3e5">

Also, the existing nav function only has function navigate to the next image, not previous ones. I think we need to update it later.

**Comment by ttaliacc** [comment]
We need to create some dummy data to test out the functionality 
@Tian-Tan Can you create some images that share same occurrences? For example, image 1, 2 and 3 are all linked to occurrence 1.

**Comment by ttaliacc** [comment]
There might be some inconsistency with our current database with the code. So we need to wait until we get the new db to see if we should update the code or it's the problem of the existing db.

**Comment by ttaliacc** [comment]
We just assume our current image path is correct, and implement the basic functionality.

Based on what we discussed before, one occurrence may have multiple images..
So the relationship between image and occurrence is 
- 1 image > 1 occurrence
- 1 occurrence >= 1 image
