### ISSUE TITLE
Image + barcode research

### ISSUE THREAD

**Issue by ttaliacc** [BU-Spark/se-Symbiota-portal#37]
Figure out how should it work and make plans

**Comment by Tian-Tan** [comment]
One image -> multiple barcodes -> multiple occurrences. So, each occurrence should have its own unique barcode. For normalization purposes, I removed the dependency of the barcode on the omoccurrences table and made it linked to the images table instead.
![Batch overhaul 2](https://github.com/BU-Spark/se-Symbiota-portal/assets/101669234/6469e4e2-4fd7-4495-973e-506c12414167)

**Comment by ttaliacc** [comment]
There might be something else other than barcode is changed, which cause the error of the occurrence display, quick entry and old entry form page.

**Comment by Tian-Tan** [comment]
Since every barcode is unique to its respective occurrence (barcode and occurrence are one-to-one relationship), it makes it easier for the frontend to have a link between the both tables for easy access. Thus, a new `occid` field is added to the images_barcode table which is a FK to the omoccurrences table.

**Comment by ttaliacc** [comment]
Currently, we conclude the relationship between the tables are:
- images -> images_barcode, if the barcode exists for the specific omoccurrences, use images -> omoccurrences and pull that occurrence up
- if the barcode does not have an associated omoccurrence, create a new occurrence

However, this logic brings up a problem: When should we check the existence of barcode? In the batch page or in the quickentry form page? Or both??

**Comment by ttaliacc** [comment]
Now, the barcode is included in the url of each occurrence. Every time before we open an occurrence, we will check the existence of barcode and occid of the corresponding images.
