### ISSUE TITLE
Clear with the details of the batch page and quick entry form

### ISSUE THREAD

**Issue by ttaliacc** [BU-Spark/se-Symbiota-portal#47]
We have some details to clarify:
- [x] what is the "status" of the batch page should be like?
- [x] what is "info need" field of the quick entry form should be like?
- [x] what is the "record created" should be like?

<img width="564" alt="Screen Shot 2023-08-09 at 10 23 10" src="https://github.com/BU-Spark/se-Symbiota-portal/assets/103902059/4af46b26-37bf-414d-b1b0-46aee2761ee0">

<img width="424" alt="Screen Shot 2023-08-09 at 10 22 53" src="https://github.com/BU-Spark/se-Symbiota-portal/assets/103902059/26c43cd2-ecad-4b8d-9c0d-88e1a2dc38a1">

<img width="284" alt="Screenshot 2023-10-06 at 14 09 20" src="https://github.com/BU-Spark/se-Symbiota-portal/assets/103902059/6fbf4d2d-9f6a-43f0-a99e-eb7d27cae0ea">

**Comment by ttaliacc** [comment]
Need to check with clients in the next meeting.

**Comment by Tian-Tan** [comment]
Conclusion after the meeting: Display errors, success messages, user logged in at the bottom. For record created field, if symbiota has timestamp then we put that, if not then we can leave it. If record is a new one, display 'new record' instead

**Comment by ttaliacc** [comment]
We have had message window that will pop up in the top of the form after any action is made.
So for the "info needed" field at the bottom, I'll put dateLastModified over there. 
<img width="211" alt="Screenshot 2023-11-08 at 11 52 36" src="https://github.com/BU-Spark/se-Symbiota-portal/assets/103902059/d49e985d-b075-4fdc-90dc-453a1c3149b0">

For the "record created" field, i'll put the "modified" time stamp there. I assume it is the record created date?
<img width="218" alt="Screenshot 2023-11-08 at 11 54 26" src="https://github.com/BU-Spark/se-Symbiota-portal/assets/103902059/d82fdbbf-5c9b-4de9-8cb8-470d05c519b6">

**Comment by ttaliacc** [comment]
Fill the fields with corresponding info with commit [87a33a5](https://github.com/BU-Spark/se-Symbiota-portal/commit/87a33a583527d8f45b933cbed1b3dc69fb0a335b)

<img width="361" alt="Screenshot 2023-11-11 at 16 27 25" src="https://github.com/BU-Spark/se-Symbiota-portal/assets/103902059/ec7ba1cd-ec57-4f19-b3ca-75ed34d1769c">
<img width="388" alt="Screenshot 2023-11-11 at 16 27 38" src="https://github.com/BU-Spark/se-Symbiota-portal/assets/103902059/1b1fc449-26df-486b-903c-f79cf0da8fc3">
