### ISSUE TITLE
Summarize symbiota progress in Summer 2023

### ISSUE THREAD

**Issue by Tian-Tan** [BU-Spark/se-Symbiota-portal#52]
Database work:
1. Add missing omoccurrences fields to the omoccurrences table.
2. Create schema to support dropdown functions. On hold for now while we wait for a reply from symbiota staff on pointers for existing typeahead functions.
3. Overhaul batch tables created in Summer 2022.
4. Manually import Harvard's sample omoccurrences and images data into the database.

**Comment by ttaliacc** [comment]
You can put this in the documentation instead
