### ISSUE TITLE
Fix PHP DOMdocument error on server side

### ISSUE THREAD

**Issue by Tian-Tan** [BU-Spark/se-Symbiota-portal#53]
Many site functions are currently not available due to the "class DOMdocument not found" error of PHP. There are currently 2 ongoing parallel attempts to fix this:
1. Create a new server from scratch locally and start a fresh installation
2. Try to fix the problem in the currently running server

**Comment by Tian-Tan** [comment]
Update on attempt 1: DOMDocument is detected correctly on a fresh installation, and so we are proceeding to mounting a new server using the same steps done and making a container.

**Comment by mmeah16** [comment]
10/26: 

Bugs in VM, needs to debug and change config files but commands are not working

Container is working, needs to figure out how to run Apache on the container

**Comment by Tian-Tan** [comment]
The containers work locally and there doesn't seem to be any errors related to DOMdocument being missing anymore. The next steps might be to try running the containers on the server, but as far as this issue goes this can be closed now.
