### ISSUE TITLE
styling consistency

### ISSUE THREAD

**Issue by ttaliacc** [BU-Spark/se-Symbiota-portal#54]
The styling of the quick entry form is a bit different from other parts of the website. If we want to upstream our work, it would be better to update our styling according

<img width="1024" alt="Screenshot 2023-10-15 at 01 34 13" src="https://github.com/BU-Spark/se-Symbiota-portal/assets/103902059/3f4311f4-2c3b-4acc-826b-0131ed635560">

<img width="1168" alt="Screenshot 2023-10-15 at 01 35 16" src="https://github.com/BU-Spark/se-Symbiota-portal/assets/103902059/d5d0d5e6-3773-4a1c-b9a3-2352e983e2bf">
Another form in the website. It should be ideal for us to update quick entry form's styling to be similar to this.

**Comment by Tian-Tan** [comment]
Update after the meeting: the styling is of very low importance and we can leave it for now

**Comment by ttaliacc** [comment]
Update the UI with 272ad71e5adb8f0434266de03ae5dbbfd37c377c
