### ISSUE TITLE
Conflict between the batch occId and universal occid

### ISSUE THREAD

**Issue by ttaliacc** [BU-Spark/se-Symbiota-portal#55]
The new quick entry form and quick entry form should have access to the same occurrence table, which means they share the same occurrence database. However, to display the occurrence within a batch and make it easier to navigate among the occurrences within the batch, we create a new "occId" when we open the occurrence in the quick entry form 

In this way, a issue will occur when we are trying to create a new occurrence. Because we will need to generate a real occid in the omoccurrence table. 

Another problem is that we use the feature "occurrenceID" to connect the image and omoccurrence table. If we create a new occurrence, how can we generate the value of this feature?

### Related to 
- #45

**Comment by ttaliacc** [comment]
There is a potential issue with using sequential _occid_ as one of the keys. When ever we delete an occurrence, having a new occid as _len(occ table)+1_ will not be unique

**Comment by Tian-Tan** [comment]
After the meeting, the conclusion is to use sequential id for internal processes and use GUID for display purposes.

**Comment by Tian-Tan** [comment]
Will be keeping this issue open until the changes are implemented in the database and frontend
