### ISSUE TITLE
Automatically assign images to batch upon ingestion

### ISSUE THREAD

**Issue by Tian-Tan** [BU-Spark/se-Symbiota-portal#64]
We need to investigate how to:
1. Create a new entry in the batch table on ingestion to signify the creation of a new batch
2. Assign all image_id from the same ingestion batch to the same batch number in the batch_XREF table

The above should probably be done in the ingestion PHP code

**Comment by ttaliacc** [comment]
Here are the related files:

**/collections/admin/specupload.php:**
-  the ingestion page 
- [http://10.210.3.94:9080/collections/admin/specupload.php?uploadtype=6&collid=1](url)

**/collections/admin/specuploadmap.php:** 
- the submit form action file. provides import edition before final data ingestion
- this page can be navigated to by clicking **analyze file** in the **specupload.php** file

**/collections/admin/specuploadprocessor.php:**
-  process the uploaded ingestion file  (core file of ingestion data processing)
- it includes all following php files and use there functions

**/classes/SpecUploadFile.php:** 
- processor of the uploaded file. It opens the file and reads its data
- check this function of it `public function uploadData($finalTransfer)`. This might be where you can make changes

**/collections/admin/specuploadprocessor.php:** 
- provides some helper functions for the file setting

**/classes/SpecUploadDwca.php:** 
- read and process dwca files in detail. For example, it maps the xml to the omoccurrence table. 
- the `public function uploadData($finalTransfer){` may have functions you want to implement. And in this function, I saw some image data update code, which you can look into.

**/classes/SpecUploadBase.php:**
- The file included by **SpecUploadDwca.php**.  It has all used sql functions.

If you have time, it ill be helpful dig into all php files included in the beginning of all above files.

**Comment by Tian-Tan** [comment]
Another important note here is that the ingestion first adds the records to a temporary table, and only moves them to the real tables after confirmation.

The temporary tables for the occurrence records and images are **uploadspectemp** and **uploadimagetemp**

**Comment by Tian-Tan** [comment]
The commit 18d847885aae248e3184083cb8b58940f3dd08d9 successfully creates a new batch upon ingestion. Further steps are: 
1. Add a GUID for the batch
2. Beautify the batch name by defaulting it to a timestamp using the PHP code
3. Automatically assign images to batch

**Comment by Tian-Tan** [comment]
To address the problems above:
1. A GUID is not necessary as we are using a batch timestamp which is unique enough to use as the batch name.
2. There is a slight problem with the timestamp being used being not too human readable. This will need a minor fix.
3. Solved in ba4b0cb0ebbe70879ddcab30100591de056ef87e

**Comment by Tian-Tan** [comment]
2. is solved by a quick fix in 0919f10d41ea7a83629d59440904e4ffb65dee2f.
